import { Request, Response } from "express";
import { catchAsync } from "../../utils/catchAsync";
import { authService } from "./auth.service";
import { sendResponse } from "../../utils/sendResponse";
import httpStatus from 'http-status-codes';
import { clearCookie, setAuthCookie } from "../../utils/cookies";


const loginUser = catchAsync(async (req: Request, res: Response) => {
      const { email, password } = req.body;
      const { user, userTokens } = await authService.loginUser(email, password);

      setAuthCookie(res, userTokens);

      sendResponse(res, {
            success: true,
            statusCode: httpStatus.OK,
            message: "User logged in successful",
            data: {
                  ...userTokens,
                  user
            }
      })
});

const logoutUser = catchAsync(async (req: Request, res: Response) => {
      clearCookie(res, "accessToken");
      clearCookie(res, "refreshToken");

      sendResponse(res, {
            success: true,
            statusCode: httpStatus.OK,
            message: "User logout successful",
            data: null
      });
});

const getNewAccessToken = catchAsync(async (req: Request, res: Response) => {
      const { refreshToken } = req.cookies;
      const tokenInfo = await authService.getNewAccessToken(refreshToken);

      setAuthCookie(res, tokenInfo);

      sendResponse(res, {
            success: true,
            statusCode: httpStatus.OK,
            message: "accessToken generated by refreshToken successfully",
            data: tokenInfo
      });
});


export const authController = {
      loginUser,
      logoutUser,
      getNewAccessToken
};